### ISSUE TITLE
Reading out of bounds backwards yields cryptic error

### ISSUE THREAD

**Issue by Eadword** [EventStore/EventStore-Client-NodeJS#117]
In one of my tests I apparently had it calling `readStream` with out of bounds values, I would expect this to either return an empty array or to at least give a somewhat useful error message.

I called ```readStream('somestream', 16, { direction: BACKWARDS, fromRevision: -1n })``` and got the error:

```
13 INTERNAL: Request message serialization failure: Cannot read property 'lo' of null

      at Object.convertToCommandError (../node_modules/@eventstore/db-client/dist/utils/CommandError.js:281:12)
      at ClientReadableStreamImpl.<anonymous> (../node_modules/@eventstore/db-client/dist/utils/handleBatchRead.js:27:38)
      at Object.onReceiveStatus (../node_modules/@grpc/grpc-js/src/client.ts:570:18)
      at Object.onReceiveStatus (../node_modules/@grpc/grpc-js/src/client-interceptors.ts:387:48)
      at ../node_modules/@grpc/grpc-js/src/call-stream.ts:243:24
```
If it matters, the stream did already have several elements in it.

I would not say this is a bug _per se_, but the way it broke makes me wonder if there could be some other edge cases?

This was tested with alpha 12.

**Comment by George-Payne** [comment]
Hi @Eadword,

Thank you for the bug report, that error is coming from the server, so I've created an issue here: #2781

I'll close this one as it should require no action on the client once it is fixed there.
