### ISSUE TITLE
All stream subscriptions have errors with filters

### ISSUE THREAD

**Issue by Eadword** [EventStore/EventStore-Client-NodeJS#124]
Now I have not tried anywhere close to all combinations, but I know in Alpha 12, I was finding that filters basically caused it to never find any events, and now with Alpha 13 it seems that filters are causing an error. I did (in Alpha 12) try playing around with regex/prefix and some different options but all seemed to return no events even when I know there should have been some.

Anyway, this is the code I expect should work:
```ts
describe('Eventstore GRPC Client', () => {
  let client: EventStoreDBClient

  beforeAll(() => {
    client = new EventStoreDBClient(
      {
        endpoint: {
          address: process.env.ES_HOSTNAME ?? 'eventstore',
          port: parseInt(process.env.ES_GRPC_PORT ?? '2113'),
        },
      },
      { insecure: true },
      {
        username: process.env.ES_USERNAME!,
        password: process.env.ES_PASSWORD!,
      },
    )
  })

  it('can subscribe to the all stream with a filter', async () => {
    jest.setTimeout(10000)
    const stream = `test_${uuidv4().replace(/\-/g, '')}`
    const events = []
    for (let i = 0; i < 10; ++i) {
      events.push(
        jsonEvent({
          type: 'test-event',
          id: uuidv4(),
          data: {
            a: i,
          },
        }),
      )
    }

    const appendRes = await client.appendToStream(stream, events.slice(0, 3), {
      expectedRevision: NO_STREAM,
    })

    const received: AllStreamResolvedEvent[] = []
    const sub = client.subscribeToAll({
      filter: { filterOn: STREAM_NAME, regex: `^${stream}$` },
      fromPosition: START,
    })
    sub.on('error', (err) => console.log(err, err?.message))
    sub.on('close', () => console.log('subscription stopped'))
    sub.on('data', (evt) => {
      console.log(`received event ${events.length}`)
      received.push(evt)
    })
    while (received.length < 3) await forMs(10)
    await client.appendToStream(stream, events.slice(3, 10), {
      expectedRevision: appendRes.nextExpectedRevision,
    })
    while (received.length < 10) await forMs(10)
    expect(received.map((e) => e.event?.id)).toStrictEqual(events.map((e) => e.id))
    await sub.unsubscribe()
  })
  ```

And this is the error I see:
```
  console.log
    UnknownError: 2 UNKNOWN: Exception was thrown by handler.
        at Object.convertToCommandError (/app/node_modules/@eventstore/db-client/dist/utils/CommandError.js:281:12)
        at ClientReadableStreamImpl.<anonymous> (/app/node_modules/@eventstore/db-client/dist/utils/OneWaySubscription.js:32:38)
        at ClientReadableStreamImpl.emit (events.js:315:20)
        at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client.ts:570:18)
        at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client-interceptors.ts:387:48)
        at /app/node_modules/@grpc/grpc-js/src/call-stream.ts:249:24
        at processTicksAndRejections (internal/process/task_queues.js:75:11) {
      code: 2,
      _raw: Error: 2 UNKNOWN: Exception was thrown by handler.
          at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/src/call.ts:81:24)
          at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client.ts:570:32)
          at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client-interceptors.ts:387:48)
          at /app/node_modules/@grpc/grpc-js/src/call-stream.ts:249:24
          at processTicksAndRejections (internal/process/task_queues.js:75:11) {
        code: 2,
        details: 'Exception was thrown by handler.',
        metadata: Metadata { internalRepr: [Map], options: {} }
      },
      type: 'unknown'
    } 2 UNKNOWN: Exception was thrown by handler.

      at OneWaySubscription.<anonymous> (eventstore-connection.spec.ts:83:38)
```

Again, in Alpha 12 this error did not occur, but filter still did not work, so I suspect there's two layers of errors here, but I also did not test extensively so I may be mistaken.

This is my eventstore configuration (from docker compose) for testing
```yaml
  eventstore:
    image: eventstore/eventstore:20.10.0-bionic
    environment:
      EVENTSTORE_START_STANDARD_PROJECTIONS: 'true'
      EVENTSTORE_INSECURE: 'true'
      EVENTSTORE_RUN_PROJECTIONS: 'All'
```

**Comment by George-Payne** [comment]
Hi Matthew, 

Thanks for the issue and reproduction. Looks like filters are currently a big hole in test cases / doc comments.

In your example:

``` ts
    const sub = client.subscribeToAll({
      filter: { filterOn: STREAM_NAME, regex: `^${stream}$` },
      fromPosition: START,
    })
```

When this is sent over GRPC you get:

```
streamIdentifier: { regex: '^my_stream$', prefixList: [] },
eventType: undefined,
max: 0,
count: undefined,
checkpointintervalmultiplier: 0
 ```
 but `max` and `checkpointintervalmultiplier` both have to be non-zero. (GRPC defaults numbers to 0 when not specified).
 
So for the time being you can work around it by changing to: 

``` ts
    const sub = client.subscribeToAll({
      filter: { filterOn: STREAM_NAME, regex: `^${stream}$`, max: 32, checkpointintervalmul: 1 },
      fromPosition: START,
    })
```

In #127 I've reworked the code around this. The helper functions `streamNameFilter` and `eventTypeFilter` now provide sensible defaults and if you pass 0, it will throw an error before its sent to the server. 

I've also opened an issue https://github.com/EventStore/EventStore/issues/2790 to improve the error message from the server.
