### ISSUE TITLE
Unable to Connect to Insecure Docker Compose

### ISSUE THREAD

**Issue by mikecann** [EventStore/EventStore-Client-NodeJS#302]
Hi, 

I have followed [the installation for the insecure docker compose](https://developers.eventstore.com/server/v21.10/installation.html#use-docker-compose) exactly and am able to open the admin UI so I know its working.

But using the example from the readme on this page I get the following error:

```
C:\dev\gangbusters\experiments\battletabs-eventsourced-spike\node_modules\@eventstore\db-client\dist\utils\CommandError.js:353
            return new UnavailableError(error);
                   ^

UnavailableError: 14 UNAVAILABLE: No connection established
    at convertToCommandError (C:\dev\gangbusters\experiments\battletabs-eventsourced-spike\node_modules\@eventstore\db-client\dist\utils\CommandError.js:353:20)
    at Object.callback (C:\dev\gangbusters\experiments\battletabs-eventsourced-spike\node_modules\@eventstore\db-client\dist\streams\appendToStream\append.js:41:65)
    at Object.onReceiveStatus (C:\dev\gangbusters\experiments\battletabs-eventsourced-spike\node_modules\@grpc\grpc-js\build\src\client.js:268:36)
    at Object.onReceiveStatus (C:\dev\gangbusters\experiments\battletabs-eventsourced-spike\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:365:141)
    at Object.onReceiveStatus (C:\dev\gangbusters\experiments\battletabs-eventsourced-spike\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:328:181)
    at C:\dev\gangbusters\experiments\battletabs-eventsourced-spike\node_modules\@grpc\grpc-js\build\src\call-stream.js:187:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 14,
  _raw: Error: 14 UNAVAILABLE: No connection established
      at Object.callErrorFromStatus (C:\dev\gangbusters\experiments\battletabs-eventsourced-spike\node_modules\@grpc\grpc-js\build\src\call.js:31:19)
      at Object.onReceiveStatus (C:\dev\gangbusters\experiments\battletabs-eventsourced-spike\node_modules\@grpc\grpc-js\build\src\client.js:268:52)
      at Object.onReceiveStatus (C:\dev\gangbusters\experiments\battletabs-eventsourced-spike\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:365:141)
      at Object.onReceiveStatus (C:\dev\gangbusters\experiments\battletabs-eventsourced-spike\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:328:181)
      at C:\dev\gangbusters\experiments\battletabs-eventsourced-spike\node_modules\@grpc\grpc-js\build\src\call-stream.js:187:78
      at processTicksAndRejections (node:internal/process/task_queues:78:11)
  for call at
      at ServiceClientImpl.makeClientStreamRequest (C:\dev\gangbusters\experiments\battletabs-eventsourced-spike\node_modules\@grpc\grpc-js\build\src\client.js:238:30)
      at ServiceClientImpl.append (C:\dev\gangbusters\experiments\battletabs-eventsourced-spike\node_modules\@grpc\grpc-js\build\src\make-client.js:105:19)   
      at C:\dev\gangbusters\experiments\battletabs-eventsourced-spike\node_modules\@eventstore\db-client\dist\streams\appendToStream\append.js:39:29
      at new Promise (<anonymous>)
      at C:\dev\gangbusters\experiments\battletabs-eventsourced-spike\node_modules\@eventstore\db-client\dist\streams\appendToStream\append.js:38:88
      at Client.execute (C:\dev\gangbusters\experiments\battletabs-eventsourced-spike\node_modules\@eventstore\db-client\dist\Client\index.js:95:30)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async simpleTest (C:\dev\gangbusters\experiments\battletabs-eventsourced-spike\dist\index.js:21:24) {
    code: 14,
    details: 'No connection established',
    metadata: Metadata { internalRepr: Map(0) {}, options: {} }
  },
  type: 'unavailable'
}
```

Any ideas?

**Comment by mikecann** [comment]
Am I missing something?

**Comment by George-Payne** [comment]
Hi Mike,

> insecure docker compose

``` ts
const client = new EventStoreDBClient({
  endpoint: "localhost:2113",
});
```

The grpc clients are secure by default, so you need to tell the client to use an insecure connection, you can either do this via the options argument:

```ts
const client = new EventStoreDBClient(
  { endpoint: "localhost:2113" },
  { insecure: true }
);
```

or via a connection string

```ts
const client = EventStoreDBClient.connectionString`esdb://localhost:2113?tls=false`;
```

You can find our connecting string helper here:

https://developers.eventstore.com/clients/grpc/#connection-details

----

> And the exact same installation method listed on the official docs:  
> https://developers.eventstore.com/server/v5/installation.html#use-docker-compose

You've linked the `v5` docs here (though you linked `v21.10` in the original issue) 

The GRPC clients are only supported on `20.6.1` upwards. 

----

If you're having trouble finding something in [the docs](https://developers.eventstore.com/clients/grpc/), a good place to look for examples are the [tests in this repo.](https://github.com/EventStore/EventStore-Client-NodeJS/tree/master/src/__test__) For example,  [under `connection/insecure`](https://github.com/EventStore/EventStore-Client-NodeJS/blob/master/src/__test__/connection/insecure.test.ts)

----

This could definitely be more explicitly spelled out in the documentation (and isn't the first issue we've had asking this so it must be tripping more people up.) I'll see about adding something.

**Comment by mikecann** [comment]
Ah gotcha thanks, I can confirm since adding `{ insecure: true }` it now works. 

I definately this this could be made more clear in the docs or perhaps the error could be more clear `UnavailableError: 14 UNAVAILABLE: No connection established` doesnt really tell you much ;)

> If you're having trouble finding something in [the docs](https://developers.eventstore.com/clients/grpc/), a good place to look for examples are the [tests in this repo.](https://github.com/EventStore/EventStore-Client-NodeJS/tree/master/src/__test__) For example, [under connection/insecure](https://github.com/EventStore/EventStore-Client-NodeJS/blob/master/src/__test__/connection/insecure.test.ts)

Although linking to tests is sometimes useful in this case it doesnt actually show me where I made a mistake as it doesnt show me that I needed to use the special flag:

![image](https://user-images.githubusercontent.com/215033/181867228-23a65838-dc83-4be0-b10f-207246094b52.png)

**Comment by George-Payne** [comment]
> I can confirm since adding `{ insecure: true }` it now works.
Great, glad you were able to get it working.

> I definately think this could be made more clear in the docs
I've added a note to the top of the docs about this to hopefully point people in the right direction. https://github.com/EventStore/documentation/pull/544

> perhaps the error could be more clear `UnavailableError: 14 UNAVAILABLE: No connection established` doesnt really tell you much 

Setting the client to insecure changes the endpoint from `https://` to `http://` so the returned error is just connection refused, meaning we can't distinguish between an incorrect endpoint, or an unavailable server, or a spelling mistake in your endpoint etc. Maybe we could add a debug log with some pointers on what to check.

>  I have solved the issue so feel free to close this.

Will do.

**Comment by alfonsodev** [comment]
I Had the same problem as @mikecann, It's obviously nice that is secure by default, I think it would be better to add a comment on the example code, since different people arrive to this repo from different places. 
And it's most likely that you are running that "hello world" in an insecure way, since I might wrong but all docker examples from the getting started guides are written with --insecure
