### ISSUE TITLE
Stock example gives UnknownError: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)  

### ISSUE THREAD

**Issue by mariobittencourt** [EventStore/EventStore-Client-NodeJS#51]
Using the current image and the stock example from the readme I get an error.
I have a single server running locally that I can access normally via 127.0.0.1:2113 using the example config https://developers.eventstore.com/server/20.6/server/installation/docker.html

```
UnknownError: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)
    at Object.exports.convertToCommandError (/home/mbneto/Development/event-store/node_modules/@eventstore/db-client/dist/utils/CommandError.js:278:12)
    at Object.callback (/home/mbneto/Development/event-store/node_modules/@eventstore/db-client/dist/command/streams/WriteEventsToStream.js:69:50)
    at Object.onReceiveStatus (/home/mbneto/Development/event-store/node_modules/@grpc/grpc-js/src/client.ts:451:26)
    at Object.onReceiveStatus (/home/mbneto/Development/event-store/node_modules/@grpc/grpc-js/src/client-interceptors.ts:434:34)
    at Object.onReceiveStatus (/home/mbneto/Development/event-store/node_modules/@grpc/grpc-js/src/client-interceptors.ts:397:48)
    at /home/mbneto/Development/event-store/node_modules/@grpc/grpc-js/src/call-stream.ts:237:24
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 13,
  _raw: Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)
      at Object.callErrorFromStatus (/home/mbneto/Development/event-store/node_modules/@grpc/grpc-js/src/call.ts:81:24)
      at Object.onReceiveStatus (/home/mbneto/Development/event-store/node_modules/@grpc/grpc-js/src/client.ts:451:36)
      at Object.onReceiveStatus (/home/mbneto/Development/event-store/node_modules/@grpc/grpc-js/src/client-interceptors.ts:434:34)
      at Object.onReceiveStatus (/home/mbneto/Development/event-store/node_modules/@grpc/grpc-js/src/client-interceptors.ts:397:48)
      at /home/mbneto/Development/event-store/node_modules/@grpc/grpc-js/src/call-stream.ts:237:24
      at processTicksAndRejections (internal/process/task_queues.js:79:11) {
    code: 13,
    details: 'Received RST_STREAM with code 2 (Internal server error)',
    metadata: Metadata { internalRepr: Map {}, options: {} }
  },
  type: 'unknown'
}
```

**Comment by George-Payne** [comment]
Hello, 
I rechecked the readme example locally and wasn't able to reproduce, 

Could you send me the following:

The first part of the output of ESDB (up to "`DEFAULT OPTIONS`"):
![image](https://user-images.githubusercontent.com/11861797/96722509-c298dd00-13ad-11eb-944d-63a5140bbc7a.png)

Your node version:

```shell
$ node -v
```

The version `@eventstore/db-client` installed:

```shell
$ yarn list --pattern @eventstore/db-client
```
or
```shell
$ npm list --pattern @eventstore/db-client
```

**Comment by mariobittencourt** [comment]
Hi George,

"ES VERSION:"             "5.0.8.0"
("HEAD"/"6b871e5659ed38775372456fb21be6a99392fddb", "Thu, 26 Mar 2020
11:42:43 +0100")
[00001,01,00:14:35.500] "OS:"                     Linux (Unix 5.4.0.52)
[00001,01,00:14:35.505] "RUNTIME:"                "5.16.0.220 (tarball Mon
Nov 26 17:22:46 UTC 2018)" (64-bit)
[00001,01,00:14:35.505] "GC:"                     "2 GENERATIONS"
[00001,01,00:14:35.505] "LOGS:"                   "/var/log/eventstore"
MODIFIED OPTIONS:

CLUSTER GOSSIP PORT:      2112 (Environment Variable)
INT IP:                   0.0.0.0 (Config File)
EXT IP:                   0.0.0.0 (Config File)
INT HTTP PREFIXES:        http://*:2112/ (Config File)
EXT HTTP PREFIXES:        http://*:2113/ (Config File)
ADD INTERFACE PREFIXES:   false (Config File)
RUN PROJECTIONS:          All (Config File)

----
node -v
v12.19.0
-----
event-store@1.0.0 /path-to-my-code/event-store
└── @eventstore/db-client@0.0.0-alpha.3

**Comment by George-Payne** [comment]
> "ES VERSION:"             "5.0.8.0"

This client is only compatable with `20.6.1` and upwards:
https://github.com/EventStore/EventStore-Client-NodeJS#eventstoredb-server-compatibility

Any of these docker tags should work:
`eventstore/eventstore:latest`
`eventstore/eventstore:20.6.1-buster-slim`
`eventstore/eventstore:20.6.1-bionic`

**Comment by mariobittencourt** [comment]
Hi, thank you. For some reason the image that got pulled was the 5.x.

Now it is working.
